# Generated by Django 3.1.2 on 2020-11-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
