# Generated by Django 3.1.2 on 2020-11-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20201119_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='unique_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('FWD', 'Forward'), ('DEF', 'Defense'), ('CNT', 'Center'), ('GOL', 'Goalie')], default='FWD', max_length=3)),
                ('goals', models.IntegerField(blank=True)),
                ('points', models.IntegerField(blank=True)),
                ('fol', models.IntegerField(blank=True)),
                ('ppg', models.IntegerField(blank=True)),
                ('shg', models.IntegerField(blank=True)),
                ('assists', models.IntegerField(blank=True)),
                ('foPercent', models.FloatField(blank=True)),
                ('shootingPercent', models.FloatField(blank=True)),
                ('toi', models.IntegerField(blank=True)),
                ('sog', models.IntegerField(blank=True)),
                ('fow', models.IntegerField(blank=True)),
                ('pim', models.IntegerField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField()),
                ('leave_date', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('homeGoals', models.IntegerField(default=0)),
                ('homePoints', models.IntegerField(default=0)),
                ('awayGoals', models.IntegerField(default=0)),
                ('awayPoints', models.IntegerField(default=0)),
                ('awayTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='main.team')),
                ('homeTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='main.team')),
            ],
        ),
    ]
