# Generated by Django 3.1.2 on 2020-11-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='leave_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match'),
        ),
    ]
