# Generated by Django 3.1.2 on 2020-11-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201119_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='foPercent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='fol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='fow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='pim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='ppg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='shg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='shootingPercent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='sog',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='toi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
