# Generated by Django 3.1.2 on 2020-11-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201119_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
