# Generated by Django 3.1.2 on 2020-12-03 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='playerlist',
            name='isDummy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='isDummy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='main.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='main.team'),
        ),
        migrations.AddField(
            model_name='playerlist',
            name='dummy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.dummy'),
        ),
        migrations.AddField(
            model_name='stats',
            name='dummy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.dummy'),
        ),
    ]
