# Generated by Django 3.1.2 on 2020-12-09 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_dummy_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
