# Generated by Django 3.1.2 on 2020-12-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201209_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerlist',
            name='dummy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dummy'),
        ),
    ]
