# Generated by Django 3.1.2 on 2020-12-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201209_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='yourTeam',
            field=models.CharField(choices=[('AW', 'Away'), ('HO', 'Home')], default='AW', max_length=2),
        ),
    ]
